model_opts:
  model: Distilling
  student_model: ResNet  
  obs_input_type:  [local_flo,scene_context,local_context,box]
  obs_length: 16
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  global_pooling: avg
  regularizer_val: 0.001
  backbone: c3d
  model_dim: 256
  n_heads: 8
  encoder_stack: 4
  feed_forward_size: 2048
  dropout_rate: 0.1
exp_opts:
  datasets:  [jaad_all] #jaad_all,jaad_beh,pie
  batch_size: [2, 2]
  epochs: [80, 40]
  lr: [5.0e-07, 1.0e-04]